using System.Text;

namespace Rh.MessageFormat.CldrGenerator.Generators;

/// <summary>
/// Generates the NumberSystems.g.cs file containing digit mappings for all numbering systems.
/// </summary>
public class NumberSystemCodeGenerator
{
    private readonly CldrConfig _config;

    public NumberSystemCodeGenerator(CldrConfig config)
    {
        _config = config;
    }

    /// <summary>
    /// Generates the NumberSystems.g.cs file.
    /// </summary>
    /// <param name="numberSystemDigits">Dictionary of number system id to digit string (10 characters: 0-9).</param>
    /// <param name="outputDir">Output directory for the generated file.</param>
    /// <param name="ct">Cancellation token.</param>
    public async Task GenerateAsync(
        IReadOnlyDictionary<string, string> numberSystemDigits,
        string outputDir,
        CancellationToken ct = default)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated from CLDR data. Do not modify manually.");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:O}");
        sb.AppendLine($"// Number system count: {numberSystemDigits.Count}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Rh.MessageFormat.CldrData.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides digit characters for numbering systems from CLDR data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class NumberSystems");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, string> _digits = new(StringComparer.Ordinal)");
        sb.AppendLine("    {");

        // Sort by key for consistent output
        foreach (var (systemId, digits) in numberSystemDigits.OrderBy(kvp => kvp.Key))
        {
            // Skip "latn" as it's the default (0-9) and doesn't need transformation
            if (systemId == "latn")
                continue;

            var escapedDigits = EscapeString(digits);
            sb.AppendLine($"        [\"{systemId}\"] = \"{escapedDigits}\",");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Tries to get digit characters for a numbering system.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"numberingSystem\">The system identifier (e.g., \"beng\", \"arab\").</param>");
        sb.AppendLine("    /// <param name=\"digits\">The 10 digits if found (index 0-9).</param>");
        sb.AppendLine("    /// <returns>True if found, false otherwise.</returns>");
        sb.AppendLine("    public static bool TryGetDigits(string numberingSystem, out string digits)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _digits.TryGetValue(numberingSystem, out digits!);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var filePath = Path.Combine(outputDir, "NumberSystems.g.cs");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);

        Console.WriteLine($"  Generated NumberSystems.g.cs with {numberSystemDigits.Count} number systems.");
    }

    private static string EscapeString(string value)
    {
        if (value == null) return "";
        var sb = new StringBuilder(value.Length * 2);
        foreach (var c in value)
        {
            if (c == '\\')
                sb.Append("\\\\");
            else if (c == '"')
                sb.Append("\\\"");
            else if (c < 0x20) // Control characters
                sb.AppendFormat("\\u{0:X4}", (int)c);
            else
                sb.Append(c);
        }
        return sb.ToString();
    }
}
